title: "HackScale's Blog"
author: "admin"
description: "Everything related to cybersecurity and ethical hacking."

email: "hackscale@zohomail.com"
twitter_username: "_hackscale_"
github_username: "HackScaleTeam"
youtube_username: "hack_scale"
#rss: rss

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
